[build]
  publish = "."
  command = "echo \"window.GEMINI_API_KEY = '$GEMINI_API_KEY';\" > js/config.local.js"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
